net.Receive("PlayerChatted", function()
    local ply = net.ReadEntity()
    local text = net.ReadString()
    chat.AddText(Color(255,246,43), "[", ply, Color(255,246,43), "]:", color_white, text)
end)